
version: "3"

services:
    
    admin:
        image: docker/frontend
        build: ./frontend
        container_name: admin
        ports:
            - 80:80
        volumes:
            - ./frontend/build:/usr/share/nginx/html
        links:
            - api    
        networks:
            - back   
    api:
        image: docker/backend
        build: ./backend
        container_name: api 
        environment: 
            - PORT=4000
        networks:
            - back                     
networks:
  back:
    driver: bridge  