
version: "3"

services:
    proxy:
        image: docker/proxy
        build: ./proxy
        container_name: proxy
        ports:
            - 80:80
        volumes:
            - ./proxy/nginx.conf:/etc/nginx/nginx.conf:ro
        networks:
            - front
            - back
    admin:
        image: docker/frontend
        build: ./frontend
        container_name: admin
        ports:
            - 88:88
        volumes:
            - ./frontend/build:/usr/share/nginx/html
        links:
            - api    
        networks:
            - back   
    api:
        image: docker/backend
        build: ./backend
        container_name: api 
        environment: 
            - PORT=4000
        networks:
            - back      
    web-public:
        image: docker/client
        build: ./client
        container_name: web-public
        volumes:
            - ./client:/usr/src/app
        ports:
            - 3000:3000
        networks:
            - back    
                              
networks:
  front:  
    driver: bridge  
  back:
    driver: bridge  