export default {
  GET_PRODUCT: 'GET_PRODUCT',
  FETCH_START_PRODUCT: 'FETCH_START_PRODUCT',
  FETCH_STOP_PRODUCT:'FETCH_STOP_PRODUCT',
  RESULT_PRODUCT: 'RESULT_PRODUCT',
  SORT_PRODUCT: 'SORT_PRODUCT',
  PAGINATION_PRODUCT_REQUEST: 'PAGINATION_PRODUCT_REQUEST',
  PAGINATION_PRODUCT: 'PAGINATION_PRODUCT',
  SERCH_PRODUCT: 'SERCH_PRODUCT',
  DELET_PRODUCT:'DELET_PRODUCT'
}
